version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.6"
  steps:
    - step: install
      command: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install myst-parser

sphinx:
  configuration: docs/source/conf.py
