version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.6"

python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
    - method: pip
      path: myst-parser

sphinx:
  configuration: docs/source/conf.py
